---
- name: VM Remove Snapshot
  hosts: localhost
  gather_facts: false
  connection: local
  vars:
    vcenter_hostname: <add_your_vc_ip_or_hostname>
    vcenter_user: <add_your_username>
    vcenter_pass: <add_your_password>
    esxhost: <add-1_esx_host-ip_in_cluster>
    datastore: TWN1ESXSVP2P.16TB_LOCAL
    vmtemplate: TWN1_2016_Template
    name: "{{ vm_name }}"
    notes: Ansible Test
    dumpfacts: False
  tasks:
    - name: Remove all snapshots
      vmware_guest_snapshot:
        validate_certs: False
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        datacenter: TWN1
        name: "{{ name }}"
        folder: ''
        state: remove_all
      delegate_to: localhost 
